server.port=${PORT:8080}
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DB:healthcare}
spring.jackson.default-property-inclusion=non_null
server.forward-headers-strategy=framework
